---
abstract: 'Templating using pure Perl code'
author:
  - 'Wolfgang Kinkeldei <wolfgang@kinkeldei.de>'
build_requires:
  Catalyst::Test: 0
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-ByCode
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.80
  Devel::Declare: 0.005007
  HTML::Entities: 1.35
  HTML::Tagset: 3.10
  List::Util: 1.21
  MIME::Base64: 3.07
  Moose: 0
  MooseX::AttributeHelpers: 0
  Test::Builder: 0.86
  Test::Builder::Tester: 1.18
  Test::Harness: 3.14
  Test::More: 0.86
  UUID::Random: 0.04
  YAML: 0.68
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
